configuration:
  backupStorageLocation:
  - bucket: <BUCKET NAME>
    provider: aws
  volumeSnapshotLocation:
  - config:
      region: us-west-2
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.7.1
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::{{ include "velero.account_id.value" }}:role/eks-velero-backup"
    schedule: "0/5 * * * *"
    template:
      ttl: "240h"
      storageLocation: default
      includedNamespaces:
      - "*"

velero:
  account_id: "{{ secret.velero-account-id.account_id }}"
