configuration:
  backupStorageLocation:
  - bucket: velero-k8s-backup-bucket
    provider: aws
  volumeSnapshotLocation:
  - config:
      region: us-west-2
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.7.1
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false

